import { RESPONSE_JSON_SCHEMA } from '../../llm/backend/tools/response-schema.js';

/**
 * Build the complete response instructions for the LLM.
 * Includes: JSON schema, response rules, and intent catalog.
 *
 * Key principle: The LLM declares WHAT it wants (intents).
 * The system resolves HOW (paths, labels, options, rendering).
 */
export function defineResponseSchema(): string {
  return [
    '## MANDATORY RESPONSE FORMAT',
    'You MUST respond with a JSON object matching this EXACT schema:',
    '',
    JSON.stringify(RESPONSE_JSON_SCHEMA, null, 2),
    '',
    '### Response Rules',
    '1. The "text" field contains your markdown response. This is what the user sees.',
    '2. The "code" field is optional — use it when you need to display a code block alongside text.',
    '3. Use "intents" to declare WHAT you want to happen. Do NOT include paths, labels, options, or any data. The system resolves everything.',
    '4. The JSON must be valid. Do NOT wrap it in code fences or markdown.',
    '5. If your response asks the user ANY question or presents ANY decision, you MUST include the appropriate REQUEST intent.',
    '6. Purely informational messages (no question, no decision needed) may omit intents.',
    '',
    '## Intent System',
    'Intents declare your intention. You say WHAT, the system decides HOW.',
    'Each intent has exactly 3 fields: type (namespace), action (verb), component (target).',
    '',
    '### A2UI Intents — UI Components',
    '',
    '**Display intents (action: SHOW):**',
    '- `{ "type": "A2UI", "action": "SHOW", "component": "ARTIFACT" }` — Show the artifact from the current phase',
    '- `{ "type": "A2UI", "action": "SHOW", "component": "RESULTS" }` — Show results card with stats',
    '- `{ "type": "A2UI", "action": "SHOW", "component": "CHART" }` — Show data chart',
    '- `{ "type": "A2UI", "action": "SHOW", "component": "ERROR" }` — Show error alert',
    '- `{ "type": "A2UI", "action": "SHOW", "component": "WARNING" }` — Show warning alert',
    '- `{ "type": "A2UI", "action": "SHOW", "component": "INFO" }` — Show info alert',
    '',
    '**Interactive intents (action: REQUEST):**',
    '- `{ "type": "A2UI", "action": "REQUEST", "component": "GATE" }` — Present gate approval (SI/NO)',
    '- `{ "type": "A2UI", "action": "REQUEST", "component": "CHOICE" }` — Present single-select options',
    '- `{ "type": "A2UI", "action": "REQUEST", "component": "CONFIRM" }` — Present yes/no confirmation',
    '- `{ "type": "A2UI", "action": "REQUEST", "component": "INPUT" }` — Request free-text input',
    '- `{ "type": "A2UI", "action": "REQUEST", "component": "MULTI_SELECT" }` — Present multi-select',
    '',
    '### WORKFLOW Intents — Lifecycle',
    '- `{ "type": "WORKFLOW", "action": "UPDATE", "component": "STATE" }` — Report current phase/progress',
    '- `{ "type": "WORKFLOW", "action": "START", "component": "PHASE" }` — Start the next phase',
    '- `{ "type": "WORKFLOW", "action": "COMPLETE", "component": "PHASE" }` — Mark current phase complete',
    '',
    '### Rules',
    '- You NEVER include paths, labels, file content, or options in intents. The system resolves all data.',
    '- You just declare the intent. Example: "I want to show an artifact" → `{ "type": "A2UI", "action": "SHOW", "component": "ARTIFACT" }`',
    '- You can have multiple intents in one response.',
    '- ORDER matters: intents are rendered in the order you declare them.',
    '',
    '### Workflow Gate Usage (CRITICAL)',
    'When a workflow has a Gate section and you have evaluated all requirements:',
    '1. Include `{ "type": "A2UI", "action": "SHOW", "component": "ARTIFACT" }` to show the artifact for review',
    '2. Include `{ "type": "A2UI", "action": "REQUEST", "component": "GATE" }` to present the gate approval',
    '3. The system handles the workflow transition automatically when the user approves.',
    '',
    '⚠️ **GATE vs CHOICE**: These are DIFFERENT:',
    '- REQUEST CHOICE = inline selection. Does NOT trigger phase transitions.',
    '- REQUEST GATE = FINAL workflow gate evaluation. Triggers phase advancement.',
    '',
    '### Common Patterns',
    '',
    '**Artifact + Gate (end of phase):**',
    '```json',
    '{',
    '  "text": "Analysis complete. Please review.",',
    '  "intents": [',
    '    { "type": "A2UI", "action": "SHOW", "component": "ARTIFACT" },',
    '    { "type": "A2UI", "action": "REQUEST", "component": "GATE" },',
    '    { "type": "WORKFLOW", "action": "UPDATE", "component": "STATE" }',
    '  ]',
    '}',
    '```',
    '',
    '**Question with choices:**',
    '```json',
    '{',
    '  "text": "Which approach do you prefer?",',
    '  "intents": [',
    '    { "type": "A2UI", "action": "REQUEST", "component": "CHOICE" }',
    '  ]',
    '}',
    '```',
    '',
    '**Pure information (no intents needed):**',
    '```json',
    '{ "text": "Here is the explanation..." }',
    '```',
  ].join('\n');
}
